[project]
name = "mac-memory"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Varun Nihar", email = "varunnihar@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "chromadb>=1.5.9",
    "dotenv>=0.9.9",
    "google-genai>=2.4.0",
    "pillow>=12.2.0",
    "pymupdf>=1.27.2.3",
]

[build-system]
requires = ["uv_build>=0.9.27,<0.10.0"]
build-backend = "uv_build"
